baseURL = "http://pentola.netlify.com/"
languageCode = "en-us"
title = "Pentola"
theme = "hugo-theme-learn"

[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
  unsafe= true

[caches]
[caches.getcsv]
  # Turn off caching for CSV files since these are updated frequently during development
  maxAge = 0

[params]
  # Prefix URL to edit current page. Will display an "Edit this page" button on top right hand corner of every page.
  # Useful to give opportunity to people to create merge request for your doc.
  # See the config.toml file from this documentation site to have an example.
  editURL = ""
  # Author of the site, will be used in meta information
  author = "Michael T. Lombardi"
  # Description of the site, will be used in meta information
  description = "Pentola is a high fantasy game where you play citizens embroiled in intrigue and adventure in a bronze age megalopolis, and where your choices and beliefs shape reality"
  # Shows a checkmark for visited pages on the menu
  showVisitedLinks = false
  # Disable search function. It will hide search bar
  disableSearch = false
  # Javascript and CSS cache are automatically busted when new version of site is generated.
  # Set this to true to disable this behavior (some proxies don't handle well this optimization)
  disableAssetsBusting = false
  # Set this to true to disable copy-to-clipboard button for inline code.
  disableInlineCopyToClipBoard = false
  # A title for shortcuts in menu is set by default. Set this to true to disable it.
  disableShortcutsTitle = false
  # When using mulitlingual website, disable the switch language button.
  disableLanguageSwitchingButton = false
  # Hide breadcrumbs in the header and only show the current page title
  disableBreadcrumb = false
  # Hide Next and Previous page buttons normally displayed full height beside content
  disableNextPrev = false
  # Order sections in menu by "weight" or "title". Default to "weight"
  ordersectionsby = "weight"
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = ""
  # Provide a list of custom css files to load relative from the `static/` folder in the site root.
  custom_css = ["css/asides.css", "css/icons.css", "css/rolltables.css"]

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-hourglass'></i>  Quickref"
identifier = "qr"
url = "/quickref"
weight = 10

[[Languages.en.menu.shortcuts]]
name = "<i class='fa fa-table'></i>  Character Keeper"
identifier = "ck"
url = "https://docs.google.com/spreadsheets/d/10LuRNxoBcWlAOi3quCigc9qa441Rof2EGfRAomKxCr8/edit?usp=sharing"
weight = 20

[[Languages.en.menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "gh"
url = "https://github.com/michaeltlombardi/pentola"
weight = 30
